config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'welcome/index'

  get 'sessions/create'

  root 'welcome#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  FOTOS = File.join Rails.root, 'public','photo_store'
  after_save :guardar_foto
    validates :titulo, :presence => { :message => "Falta el título" }
    validates :body, :presence => { :message => "Falta el Cuerpo del artículo" }

  def photo=(file_data)
  	unless file_data.blank?
  		@file_data = file_data
  		self.extension = file_data.original_filename.split('.').last.downcase
  		
  	end
  	
  end
  def photo_filename
  	File.join FOTOS, "#{id}.#{extension}"
  end
  def photo_path
  	"/photo_store/#{id}.#{extension}"
  end

  def has_photo?
  	File.exists? photo_filename
  end
  


  private

  def guardar_foto
  	if @file_data
  		FileUtils.mkdir_p FOTOS
  		File.open(photo_filename, 'wb') do |f|
  			f.write(@file_data.read)
  		end
  		@file_data = nil
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def check_user
  	if session[:user_id] == nil
  		render "welcome/index"
  	end
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :check_author, only: [:edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
 if session[:user_id] == nil
      redirect_to root_url, flash[:notice] => "logeate primero"
    end
    else
    @posts = Post.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
     respond_to do |format|
     format.html # show.html.erb
      format.xml  { render :xml => @article }
      format.json { render :json => @article }
      end
end
  # GET /posts/1
  # GET /posts/1.json
  def show
    respond_to do |format|
     format.html # show.html.erb
      format.xml  { render :xml => @article }
      format.json { render :json => @article }
   end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])

  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @user = User.find(session[:user_id])
    @post.user = @user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #checar autor para editar
  def check_author
    if session[:user_id] != @post.user_id
      redirect_to posts_path,:notice => "si no es tuyo no lo puedes editar"
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :titulo, :body, :photo)
    end
    def user_params
      params.require(:post).permit(:uid, :user_id, :name)
    end
  end 

app/controllers/sessions_controller.rb
#Controlador de Sesiones
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	 if session[:user_id] == nil
  	render()
else
 id_user =  session[:user_id]
     @user = User.find(session[:user_id])

end
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog10</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target=".subnav" data-offset="50" screen_capture_injected="true">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&appId=1455405191368814&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="container">
<!-- empieza bootstrap barra de navegacion-->
<nav class="navbar navbar" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Inicio</a>
  </div>
   <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/posts">Post</a></li>
      
    </ul> 
  </div>
<div>
  <ul class="nav navbar-nav">
     <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in", "/auth/facebook", id: "sign_in" %>
  <% end %> 
</ul>
</div>
</nav>
</div>


<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {multipart: true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
 
  <div class="field">
    <%= f.label :photo %>
     <%= f.file_field :photo%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<ul class='thumbnails' id='posts'>
  <% @posts.each do |post| %>
    <div id='post'>
      <li class='span3'>
       <div class='thumbnail'>
        <div class='caption'>
          <h3><%= post.titulo %></h3>
          <img src="http://graph.facebook.com/<%= "#{post.user.try(:uid)}" %>/picture?type=normal" alt="..." class="img-circle">
           <h4><span class="text-muted"><%= "#{post.user.try(:name)} "%></span></h4>
       <h4><small class="text-muted"><%= post.created_at.to_formatted_s(:long_ordinal) %></small></h4>
       <small><b><%= link_to "Leer...", post %></b></small>
          </div>
        <% if post.has_photo? %>
          <%= image_tag post.photo_path %>
         <% end %> 
         
        </div>
       </li>
   </div>
      </li>
  <% end %>
</ul>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @post.titulo %>
</p>

<p>
	<% if @post.has_photo? %>
 		<%= image_tag @post.photo_path%>
 	<% else %>
 		<b>Problema al cargar Foto</b>
 	<% end %>		
</p>

<p>
	<b>Body:</b>
	<%= simple_format @post.body, :class => "lead" %>
</p>
<div>
<h4>creado a:</h4>
<small><%= @post.created_at %></small>
<h3>hecho por:</h3>
<small><%= @post.user.try(:name) %></small>
</div>
<div class="fb-comments" data-href="<%=request.original_url%>" data-numposts="5" data-colorscheme="light"></div>
<div>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/welcome/index.html.erb
<div class="container">
<div class='jumbotron'>

	        <% if session[:user_id] == nil %>
	        	<h1>Bienvenido Metro Post</h1>
				<h2>Porfavor logueate!!!</h2>
			<%else%>
				<h1>Welcome to Metro Post</h1>
				 <img src="http://graph.facebook.com/<%= @user.uid %>/picture?type=normal" alt="..." class="img-circle">
 				<h3><%= @user.name %></h3>
 				<h5>Miembro desde: <%= @user.created_at.to_formatted_s(:long) %></h5>
	       <% end %> 

</div>
</div>